<?php

return [
    'listings' => [
        'manage' => 'إدارة الإعلانات',
        'view_manage_all' => 'عرض وإدارة جميع الإعلانات في النظام',
        'search_placeholder' => 'ابحث بعنوان الإعلان',
        'all_status' => 'كل الحالات',
        'title' => 'العنوان',
        'user' => 'المستخدم',
        'status_col' => 'الحالة',
        'price' => 'السعر',
        'created' => 'تاريخ الإنشاء',
        'actions' => 'الإجراءات',
        'no_more_to_load' => 'لا توجد إعلانات أخرى للتحميل',

        'approve' => 'موافقة',
        'reject' => 'رفض',
        'already_reviewed' => 'تمت مراجعة هذا الإعلان بالفعل.',
        'back_to_pending' => 'العودة إلى الإعلانات المعلقة',
        'approve_listing' => 'موافقة على الإعلان',
        'approve_confirm' => 'هل أنت متأكد أنك تريد الموافقة على هذا الإعلان؟ سيتم نشره.',
        'reject_listing' => 'رفض الإعلان',
        'reject_confirm' => 'هل أنت متأكد أنك تريد رفض هذا الإعلان؟ سيتم إخطار المستخدم.',
        'cancel' => 'إلغاء',

        'status' => [
            'pending' => 'معلق',
            'approved' => 'مقبول',
            'rejected' => 'مرفوض',
            'sold' => 'تم التأجير',
            'archived' => 'مؤرشف',
        ],

        'na' => 'غير متوفر',
        'preview' => 'معاينة',
        'none_found' => 'لا توجد إعلانات',
    ],

    'reports' => [
        'review_title' => 'مراجعة البلاغ',
        'review_annotate' => 'مراجعة البلاغ وإضافة ملاحظة',
        'no_broker' => 'لا يوجد وسيط',
        'view_details' => 'عرض التفاصيل',
        'listing_not_available' => 'الإعلان غير متاح',
        'details' => 'تفاصيل البلاغ',
        'reason' => 'السبب:',
        'description' => 'الوصف:',
        'comment_optional' => 'ملاحظة (اختياري)',
        'add_note' => 'أضف ملاحظة قصيرة عن المراجعة',
        'set_reviewed' => 'تعيين كمراجَع',
        'back' => 'رجوع',
        'only_admins' => 'فقط المسؤولون يمكنهم مراجعة البلاغات.',
        'reviewed' => 'تمت المراجعة',
        'reviewed_by' => 'تمت المراجعة بواسطة',
        'comment' => 'ملاحظة',
        'back_to_reports' => 'العودة إلى البلاغات',
        'delete_modal_title' => 'حذف البلاغ',
        'delete_modal_body' => 'هل أنت متأكد أنك تريد حذف هذا البلاغ؟ لا يمكن التراجع عن هذا الإجراء.',
        'delete_modal_cancel' => 'إلغاء',
        'delete_modal_confirm' => 'حذف',
    ],

    'trust_requests' => [
        'management' => 'إدارة طلبات التوثيق',
        'review_manage' => 'مراجعة وإدارة طلبات توثيق المستخدمين',
        'user' => 'المستخدم',
        'email' => 'البريد الإلكتروني',
        'phone' => 'الهاتف',
        'status' => 'الحالة',
        'submitted' => 'تاريخ الإرسال',
        'action' => 'الإجراء',
        'pending' => 'معلق',
        'approved' => 'مقبول',
        'declined' => 'مرفوض',
        'review' => 'مراجعة',
        'none_found' => 'لا توجد طلبات توثيق',
        'na' => 'غير متوفر',
        'back' => 'رجوع',
        'review_title' => 'مراجعة طلب التوثيق',
        'cancel' => 'إلغاء',
        'decline' => 'رفض',
    ],

    'users' => [
        'manage' => 'إدارة المستخدمين',
        'view_manage_all' => 'عرض وإدارة جميع المستخدمين في النظام',
        'search_placeholder' => 'ابحث بالاسم أو البريد أو اسم المستخدم',
        'all_status' => 'كل الحالات',
        'banned' => 'محظور',
        'admin' => 'مسؤول',
        'moderator' => 'مشرف',
        'broker' => 'وسيط',
        'user' => 'مستخدم',
        'avatar' => 'الصورة',
        'name' => 'الاسم',
        'status' => 'الحالة',
        'date_joined' => 'تاريخ الانضمام',
        'details' => 'التفاصيل',

        'manage_label' => 'إدارة المستخدمين',
        'no_more_users' => 'لا يوجد مزيد من المستخدمين',
        'loading_more_users' => 'جاري تحميل المزيد...',

        'user_details' => 'تفاصيل المستخدم',
        'back' => 'رجوع',
        'personal_info' => 'المعلومات الشخصية',
        'nickname' => 'الاسم',
        'username' => 'اسم المستخدم',
        'phone' => 'الهاتف',
        'role' => 'الدور',
        'trust_status' => 'حالة التوثيق',
        'account_details' => 'تفاصيل الحساب',
        'email_verified' => 'البريد مُفعّل',
        'not_verified' => 'غير مُفعّل',
        'member_since' => 'عضو منذ',
        'last_updated' => 'آخر تحديث',
        'trust_level' => 'مستوى الثقة',
        'actions' => 'الإجراءات',
        'ban' => 'حظر المستخدم',
        'unban' => 'إلغاء الحظر',
        'restrict' => 'تقييد المستخدم',
        'revoke_moderator' => 'إلغاء المشرف',
        'make_moderator' => 'تعيين كمشرف',
        'ban_reason' => 'سبب الحظر',
        'ban_reason_placeholder' => 'أدخل سبب حظر هذا المستخدم',
        'cancel' => 'إلغاء',
        'unban_confirm' => 'هل أنت متأكد أنك تريد إلغاء حظر هذا المستخدم؟',
        'restrict_confirm' => 'هل أنت متأكد أنك تريد تقييد هذا المستخدم؟ لن يتمكن من نشر الإعلانات.',
        'admin_password' => 'كلمة مرور المسؤول',
        'admin_password_placeholder' => 'أدخل كلمة مرور المسؤول للتأكيد',
        'revoke_moderator_confirm' => 'هل أنت متأكد أنك تريد إزالة صلاحية المشرف من هذا المستخدم؟',
        'make_moderator_confirm' => 'هل أنت متأكد أنك تريد ترقية هذا المستخدم إلى مشرف؟',
        'statistics' => 'الإحصائيات',
        'active_listings' => 'الإعلانات النشطة',
        'sold_listings' => 'الإعلانات المؤجرة',
        'total_listings' => 'إجمالي الإعلانات',
    ],

    'dashboard' => [
        'quick_actions' => 'إجراءات سريعة',
        'view_trust_requests' => 'عرض طلبات التوثيق',
        'review_listings' => 'مراجعة الإعلانات',
        'settings' => 'الإعدادات',
        'total_users' => 'إجمالي المستخدمين',
        'total_listings' => 'إجمالي الإعلانات',
        'reports' => 'البلاغات',
        'trusted_users' => 'المستخدمون الموثقون',
        'sold_listings' => 'الإعلانات المؤجرة',
    ],

    'pending_listings' => [
        'title' => 'العنوان',
        'user' => 'المستخدم',
        'location' => 'الموقع',
        'price' => 'السعر',
        'actions' => 'الإجراءات',
        'republish_badge' => 'إعادة نشر',
        'review_and_approve' => 'مراجعة الإعلانات المعلقة والموافقة عليها',
        'preview' => 'معاينة',
        'approve' => 'موافقة',
        'reject' => 'رفض',
        'approve_modal_title' => 'موافقة على الإعلان',
        'approve_modal_body' => 'هل أنت متأكد أنك تريد الموافقة على هذا الإعلان؟ سيتم نشره.',
        'cancel' => 'إلغاء',
        'reject_modal_title' => 'رفض الإعلان',
        'reject_modal_body' => 'هل أنت متأكد أنك تريد رفض هذا الإعلان؟ سيتم إخطار المستخدم.',
    ],

    'pending_users' => [
        'header' => 'المستخدمون المعلقون',
        'subheader' => 'مراجعة والموافقة على تسجيلات المستخدمين المعلقة',
        'username' => 'اسم المستخدم',
        'email' => 'البريد الإلكتروني',
        'submitted_data' => 'البيانات المقدمة',
        'view_data' => 'عرض البيانات',
        'approve' => 'موافقة',
        'reject' => 'رفض',
        'actions' => 'الإجراءات',
    ],

    'reports_page' => [
        'header' => 'البلاغات',
        'subheader' => 'عرض وإدارة بلاغات الإعلانات',
        'search_placeholder' => 'ابحث بالإعلان أو المُبلّغ أو السبب',
        'all_status' => 'كل الحالات',
        'pending' => 'معلق',
        'reviewed' => 'تمت المراجعة',
        'filter' => 'فلترة',
        'listing' => 'الإعلان',
        'reporter' => 'المُبلّغ',
        'reason' => 'السبب',
        'status' => 'الحالة',
        'created' => 'تاريخ الإنشاء',
        'no_actions' => 'لا توجد إجراءات',
    ],

    'misc' => [
        'users_statistics' => 'إحصائيات المستخدمين',
        'listings_statistics' => 'إحصائيات الإعلانات',
        'enter_email_reset' => 'أدخل بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.',
        'account_banned' => 'تم حظر الحساب',
        'account_suspended' => 'تم تعليق الحساب',
        'username_colon' => 'اسم المستخدم:',
        'account_suspended_message' => 'تم تعليق حسابك بواسطة فريق الإدارة.',
        'believe_incorrect' => 'إذا كنت تعتقد أن هذا خطأ',
        'contact_support_prompt' => 'يرجى التواصل مع الدعم مع اسم المستخدم وتفاصيل الحساب. نحن هنا للمساعدة.',
        'contact_support' => 'تواصل مع الدعم',
        'processing' => 'جاري المعالجة...',
        'no_pending_agreements' => 'لا توجد اتفاقيات معلقة',
        'accepted_thanks' => 'شكرًا لك! لقد قبلت الشروط والسياسة',
        'error_accepting' => 'حدث خطأ أثناء قبول الاتفاقيات',
        'arabic' => 'العربية',
        'english' => 'الإنجليزية',
    ],

    'email' => [
        'trust_accepted_headline' => 'تمت الموافقة على التحقق من الثقة!',
        'trust_accepted_greeting' => 'مرحباً :name،',
        'trust_accepted_intro' => 'تهانينا! تمت الموافقة على طلب التحقق من الثقة.',
        'trust_accepted_verified' => 'أصبحت الآن مستخدمًا موثقًا في سكن.',
        'trust_accepted_next_steps' => 'ماذا يمكنك أن تفعل الآن؟',
        'trust_accepted_can_post' => 'يمكنك الآن نشر الإعلانات والاستفادة من جميع الميزات.',
        'trust_accepted_button' => 'نشر إعلان جديد',

        'trust_rejected_headline' => 'تم رفض التحقق من الثقة',
        'trust_rejected_greeting' => 'مرحباً :name،',
        'trust_rejected_intro' => 'للأسف، تم رفض طلب التحقق من الثقة من قبل فريقنا.',
        'trust_rejected_reason_title' => 'سبب الرفض',
        'trust_rejected_what_to_do' => 'ماذا يجب أن تفعل؟',
        'trust_rejected_resubmit' => 'يمكنك مراجعة معلوماتك وإعادة إرسال الطلب.',
        'trust_rejected_button' => 'إعادة إرسال طلب التحقق',

        'points_added_headline' => 'تمت إضافة نقاط إلى حسابك',
        'points_added_greeting' => 'مرحباً :name،',
        'points_added_received' => 'لقد استلمت :points نقطة.',
        'points_added_reason' => 'السبب: :reason',
        'points_added_reason_default' => 'تمت إضافة النقاط بواسطة الإدارة.',
        'points_added_your_points' => 'رصيد نقاطك',
        'points_added_balance' => 'لديك الآن :points نقطة.',
        'points_added_uses' => 'يمكنك استخدام نقاطك لـ:',
        'points_added_use1' => 'نشر إعلانات جديدة',
        'points_added_use2' => 'ترقية باقتك',
        'points_added_use3' => 'فتح ميزات إضافية',
        'points_added_use4' => 'المشاركة في العروض',
        'points_added_button' => 'الذهاب لمتجر النقاط',
        'points_added_thanks' => 'شكرًا لاستخدامك سكن!',

        'listing_approved_headline' => 'تمت الموافقة على إعلانك!',
        'listing_approved_greeting' => 'مرحباً :name،',
        'listing_approved_intro' => 'تمت الموافقة على إعلانك ":title" وهو الآن منشور.',
        'listing_approved_visibility' => 'إعلانك الآن مرئي لجميع المستخدمين.',
        'listing_approved_whats_next' => 'ماذا بعد؟',
        'listing_approved_action1' => 'شارك إعلانك مع الأصدقاء',
        'listing_approved_action2' => 'رد بسرعة على الاستفسارات',
        'listing_approved_action3' => 'حافظ على تحديث إعلانك',
        'listing_approved_action4' => 'ضعه كـ تم التأجير عند الانتهاء',
        'listing_approved_button' => 'عرض الإعلان',
        'listing_approved_footer' => 'شكرًا لاستخدامك سكن!',

        'listing_rejected_headline' => 'تم رفض إعلانك',
        'listing_rejected_greeting' => 'مرحباً :name،',
        'listing_rejected_intro' => 'لم تتم الموافقة على إعلانك ":title".',
        'listing_rejected_reason' => 'السبب: :reason',
        'listing_rejected_reason_default' => 'غير محدد.',
        'listing_rejected_can_do' => 'ماذا يمكنك أن تفعل؟',
        'listing_rejected_action1' => 'تعديل الإعلان',
        'listing_rejected_action2' => 'مراجعة الإرشادات',
        'listing_rejected_action3' => 'التواصل مع الدعم',
        'listing_rejected_action4' => 'إعادة الإرسال للمراجعة',
        'listing_rejected_guidelines' => 'الإرشادات:',
        'listing_rejected_guideline1' => 'لا محتوى محظور',
        'listing_rejected_guideline2' => 'معلومات دقيقة فقط',
        'listing_rejected_guideline3' => 'لا إعلانات مكررة',
        'listing_rejected_guideline4' => 'احترام الشروط',
        'listing_rejected_resubmit' => 'يمكنك تعديل إعلانك وإعادة إرساله للمراجعة.',

        'listing_expired_headline' => 'انتهت صلاحية إعلانك',
        'listing_expired_greeting' => 'مرحباً :name،',
        'listing_expired_intro' => 'انتهت صلاحية إعلانك ":title".',
        'listing_expired_duration' => 'الإعلانات نشطة لمدة محدودة.',
        'listing_expired_reactivate_title' => 'كيفية إعادة التفعيل',
        'listing_expired_reactivate_intro' => 'يمكنك إعادة تفعيل إعلانك من لوحة التحكم.',
        'listing_expired_button' => 'عرض الإعلان',
        'listing_expired_tips' => 'نصائح:',
        'listing_expired_tip1' => 'حدّث تفاصيل إعلانك',
        'listing_expired_tip2' => 'تحقق من حالة باقتك',
        'listing_expired_tip3' => 'تواصل مع الدعم عند الحاجة',
        'listing_expired_tip4' => 'روّج لإعلانك',
        'listing_expired_urgency' => 'أعد التفعيل قريبًا لتجنب فقدان المهتمين.',

        'listing_sold_prompt_headline' => 'لديك :count طلب! هل تريد وضع الإعلان كمؤجر؟',
        'listing_sold_prompt_greeting' => 'مرحباً :name،',
        'listing_sold_prompt_intro' => 'حصل إعلانك ":title" على :count طلب.',
        'listing_sold_prompt_action' => 'إذا تم تأجير العقار، ضع الإعلان كـ تم التأجير.',
        'listing_sold_prompt_mark_button' => 'وضع كـ تم التأجير',
        'listing_sold_prompt_why_mark' => 'لماذا وضعه كمؤجر؟',
        'listing_sold_prompt_benefit1' => 'يساعدنا على إبقاء الإعلانات محدثة',
        'listing_sold_prompt_benefit2' => 'يحسن سمعتك',
        'listing_sold_prompt_benefit3' => 'يُخطر المهتمين',
        'listing_sold_prompt_benefit4' => 'يفتح ميزات جديدة',
        'listing_sold_prompt_other_actions' => 'إذا لم يتم التأجير، يمكنك تجاهل هذه الرسالة.',
        'listing_sold_prompt_thanks' => 'شكرًا لاستخدامك سكن!',
    ],

    'legal_documents' => [
        'acceptances_for' => 'القبولات لـ :type إصدار :version',
        'total_acceptances' => 'إجمالي القبولات',
        'search_user_email' => 'ابحث باسم المستخدم أو البريد الإلكتروني',
        'search' => 'بحث',
        'user' => 'المستخدم',
        'email' => 'البريد الإلكتروني',
        'accepted_at' => 'تاريخ القبول',
        'ip_address' => 'عنوان IP',
        'browser' => 'المتصفح',
        'na' => 'غير متوفر',
        'no_acceptances' => 'لا توجد قبولات بعد',

        'new_version' => 'إصدار جديد',
        'create_trigger' => 'إنشاء إصدار جديد سيجبر جميع المستخدمين على إعادة قبول المستند',
        'latest_version' => 'آخر إصدار',
        'version_colon' => 'الإصدار:',
        'published_colon' => 'تاريخ النشر:',
        'version_number' => 'رقم الإصدار',
        'versioning_hint' => 'استخدم ترقيم الإصدارات (v1.0) أو ترقيمًا حسب التاريخ',
        'document_content' => 'محتوى المستند',
        'document_content_en' => 'محتوى المستند (الإنجليزية)',
        'document_content_ar' => 'محتوى المستند (العربية)',
        'enter_content' => 'أدخل المحتوى الكامل لـ :type',
        'html_hint' => 'يمكنك استخدام HTML للتنسيق',
        'structure_hint_title' => 'هيكلة مقترحة',
        'structure_hint_body' => 'استخدم عناوين مع خاصية <code>id</code> وضع التفاصيل تحت كل عنوان. مثال:<br><code>&lt;h2 id="data-usage"&gt;استخدام البيانات&lt;/h2&gt;</code><br><code>&lt;p&gt;...التفاصيل...&lt;/p&gt;</code><br><code>&lt;h2 id="cookies"&gt;ملفات تعريف الارتباط&lt;/h2&gt;</code><br><code>&lt;p&gt;...التفاصيل...&lt;/p&gt;</code>',
        'publish_confirm' => 'نشر هذا الإصدار سيجبر جميع المستخدمين على قبول :type الجديد قبل المتابعة',
        'cancel' => 'إلغاء',
        'publish_version' => 'نشر الإصدار',

        'management' => 'إدارة المستندات القانونية',
        'manage_publish' => 'إدارة ونشر إصدارات جديدة من الشروط وسياسة الخصوصية',
        'terms' => 'الشروط والأحكام',
        'policy' => 'سياسة الخصوصية',
        'version' => 'الإصدار',
        'active' => 'نشط',
        'archived' => 'مؤرشف',
        'no_versions' => 'لا توجد إصدارات منشورة بعد',
        'create_first_version' => 'إنشاء أول إصدار',
        'how_it_works' => 'كيف يعمل',
        'trigger_reaccept' => 'إنشاء إصدار جديد سيجبر المستخدمين على إعادة القبول',
        'auto_archive' => 'يتم أرشفة الإصدارات السابقة تلقائيًا عند نشر إصدار جديد',
        'user_modal' => 'سيظهر للمستخدمين تنبيه يطلب قبول الإصدار الجديد',
        'acceptance_tracking' => 'يتم تتبع القبولات مع عنوان IP ووكيل المستخدم والتوقيت',

        'back' => 'رجوع',
        'version_details' => 'تفاصيل إصدار المستند',
        'type' => 'النوع',
        'published' => 'تاريخ النشر',
        'content_preview' => 'معاينة المحتوى',
        'acceptance_stats' => 'إحصائيات القبول',
        'users_accepted' => 'المستخدمون الذين قبلوا',
        'users_still_need' => 'مستخدمون لم يقبلوا بعد',
        'actions' => 'إجراءات',
        'view_acceptances' => 'عرض القبولات',
        'create_new_version' => 'إنشاء إصدار جديد',
        'archived_info' => 'هذا الإصدار مؤرشف. أنشئ إصدارًا جديدًا لإجبار المستخدمين على قبول التحديثات.',
    ],
];
