<?php

return [
    'subject_user_welcome' => 'مرحباً بك في سكن!',
    'subject_trust_request_accepted' => 'تم قبول طلب التوثيق',
    'subject_trust_request_rejected' => 'تم رفض طلب التوثيق',
    'subject_listing_approved' => 'تمت الموافقة على إعلانك',
    'subject_listing_rejected' => 'تم رفض إعلانك',
    'subject_listing_expired' => 'انتهت صلاحية إعلانك',
    'subject_points_added' => 'تمت إضافة نقاط إلى حسابك',
    'subject_listing_sold_prompt' => 'إعلانك لديه طلبات متعددة',
    'subject_plan_auto_renew_insufficient' => 'اشترِ نقاط لتجديد باقتك',
    'subject_default' => 'إشعار من سكن',

    'welcome_headline' => 'مرحباً بك في سكن!',
    'welcome_greeting' => 'مرحباً :name،',
    'welcome_intro' => 'يسعدنا انضمامك إلى مجتمع سكن.',
    'welcome_account_created' => 'تم إنشاء حسابك بنجاح.',
    'welcome_whats_next' => 'ماذا بعد؟',
    'welcome_step1' => 'أكمل ملفك الشخصي.',
    'welcome_step2' => 'فعّل بريدك الإلكتروني.',
    'welcome_step3' => 'تصفح الإعلانات واحفظ المفضلة.',
    'welcome_step4' => 'انشر أول إعلان لك عندما تكون جاهزاً.',
    'welcome_support' => 'إذا احتجت أي مساعدة، فقط قم بالرد على هذا البريد وسنساعدك.',
    'welcome_button' => 'تأكيد البريد الإلكتروني',
    'welcome_footer' => 'مع تحياتنا',

    'trust_accepted_headline' => 'تمت الموافقة على التحقق من الثقة!',
    'trust_accepted_greeting' => 'مرحباً :name،',
    'trust_accepted_intro' => 'تهانينا! تمت الموافقة على طلب التحقق من الثقة.',
    'trust_accepted_verified' => 'أصبحت الآن مستخدمًا موثقًا في سكن.',
    'trust_accepted_next_steps' => 'ماذا يمكنك أن تفعل الآن؟',
    'trust_accepted_can_post' => 'يمكنك الآن نشر الإعلانات والاستفادة من جميع الميزات.',
    'trust_accepted_button' => 'نشر إعلان جديد',

    'trust_rejected_headline' => 'تم رفض التحقق من الثقة',
    'trust_rejected_greeting' => 'مرحباً :name،',
    'trust_rejected_intro' => 'للأسف، تم رفض طلب التحقق من الثقة من قبل فريقنا.',
    'trust_rejected_reason_title' => 'سبب الرفض',
    'trust_rejected_what_to_do' => 'ماذا يجب أن تفعل؟',
    'trust_rejected_resubmit' => 'يمكنك مراجعة معلوماتك وإعادة إرسال الطلب.',
    'trust_rejected_button' => 'إعادة إرسال طلب التحقق',

    'points_added_headline' => 'تمت إضافة نقاط إلى حسابك',
    'points_added_greeting' => 'مرحباً :name،',
    'points_added_received' => 'لقد استلمت :points نقطة.',
    'points_added_reason' => 'السبب: :reason',
    'points_added_reason_default' => 'تمت إضافة النقاط بواسطة الإدارة.',
    'points_added_your_points' => 'رصيد نقاطك',
    'points_added_balance' => 'لديك الآن :points نقطة.',
    'points_added_uses' => 'يمكنك استخدام نقاطك لـ:',
    'points_added_use1' => 'نشر إعلانات جديدة',
    'points_added_use2' => 'ترقية باقتك',
    'points_added_use3' => 'فتح ميزات إضافية',
    'points_added_use4' => 'المشاركة في العروض',
    'points_added_button' => 'الذهاب لمتجر النقاط',
    'points_added_thanks' => 'شكرًا لاستخدامك سكن!',

    'listing_approved_headline' => 'تمت الموافقة على إعلانك!',
    'listing_approved_greeting' => 'مرحباً :name،',
    'listing_approved_intro' => 'تمت الموافقة على إعلانك ":title" وهو الآن منشور.',
    'listing_approved_visibility' => 'إعلانك الآن مرئي لجميع المستخدمين.',
    'listing_approved_whats_next' => 'ماذا بعد؟',
    'listing_approved_action1' => 'شارك إعلانك مع الأصدقاء',
    'listing_approved_action2' => 'رد بسرعة على الاستفسارات',
    'listing_approved_action3' => 'حافظ على تحديث إعلانك',
    'listing_approved_action4' => 'ضعه كـ تم التأجير عند الانتهاء',
    'listing_approved_button' => 'عرض الإعلان',
    'listing_approved_footer' => 'شكرًا لاستخدامك سكن!',

    'listing_rejected_headline' => 'تم رفض إعلانك',
    'listing_rejected_greeting' => 'مرحباً :name،',
    'listing_rejected_intro' => 'لم تتم الموافقة على إعلانك ":title".',
    'listing_rejected_reason' => 'السبب: :reason',
    'listing_rejected_reason_default' => 'غير محدد.',
    'listing_rejected_can_do' => 'ماذا يمكنك أن تفعل؟',
    'listing_rejected_action1' => 'تعديل الإعلان',
    'listing_rejected_action2' => 'مراجعة الإرشادات',
    'listing_rejected_action3' => 'التواصل مع الدعم',
    'listing_rejected_action4' => 'إعادة الإرسال للمراجعة',
    'listing_rejected_guidelines' => 'الإرشادات:',
    'listing_rejected_guideline1' => 'لا محتوى محظور',
    'listing_rejected_guideline2' => 'معلومات دقيقة فقط',
    'listing_rejected_guideline3' => 'لا إعلانات مكررة',
    'listing_rejected_guideline4' => 'احترام الشروط',
    'listing_rejected_resubmit' => 'يمكنك تعديل إعلانك وإعادة إرساله للمراجعة.',

    'listing_expired_headline' => 'انتهت صلاحية إعلانك',
    'listing_expired_greeting' => 'مرحباً :name،',
    'listing_expired_intro' => 'انتهت صلاحية إعلانك ":title".',
    'listing_expired_duration' => 'الإعلانات نشطة لمدة محدودة.',
    'listing_expired_reactivate_title' => 'كيفية إعادة التفعيل',
    'listing_expired_reactivate_intro' => 'يمكنك إعادة تفعيل إعلانك من لوحة التحكم.',
    'listing_expired_button' => 'عرض الإعلان',
    'listing_expired_tips' => 'نصائح:',
    'listing_expired_tip1' => 'حدّث تفاصيل إعلانك',
    'listing_expired_tip2' => 'تحقق من حالة باقتك',
    'listing_expired_tip3' => 'تواصل مع الدعم عند الحاجة',
    'listing_expired_tip4' => 'روّج لإعلانك',
    'listing_expired_urgency' => 'أعد التفعيل قريبًا لتجنب فقدان المهتمين.',

    'listing_sold_prompt_headline' => 'لديك :count طلب! هل تريد وضع الإعلان كمؤجر؟',
    'listing_sold_prompt_greeting' => 'مرحباً :name،',
    'listing_sold_prompt_intro' => 'حصل إعلانك ":title" على :count طلب.',
    'listing_sold_prompt_action' => 'إذا تم تأجير العقار، ضع الإعلان كـ تم التأجير.',
    'listing_sold_prompt_mark_button' => 'وضع كـ تم التأجير',
    'listing_sold_prompt_why_mark' => 'لماذا وضعه كمؤجر؟',
    'listing_sold_prompt_benefit1' => 'يساعدنا على إبقاء الإعلانات محدثة',
    'listing_sold_prompt_benefit2' => 'يحسن سمعتك',
    'listing_sold_prompt_benefit3' => 'يُخطر المهتمين',
    'listing_sold_prompt_benefit4' => 'يفتح ميزات جديدة',
    'listing_sold_prompt_other_actions' => 'إذا لم يتم التأجير، يمكنك تجاهل هذه الرسالة.',
    'listing_sold_prompt_thanks' => 'شكرًا لاستخدامك سكن!',

    'plan_auto_renew_insufficient_headline' => 'لا توجد نقاط كافية للتجديد التلقائي',
    'plan_auto_renew_insufficient_greeting' => 'مرحباً :name،',
    'plan_auto_renew_insufficient_body' => 'ستنتهي باقتك ":plan" في :date. التجديد التلقائي مُفعّل، لكن تحتاج :cost نقطة ورصيدك الحالي :balance نقطة.',
    'plan_auto_renew_insufficient_cta' => 'اشترِ نقاط الآن للحفاظ على إعلاناتك نشطة.',
    'plan_auto_renew_insufficient_button' => 'شراء نقاط',

    'signature_closing' => 'مع تحياتنا',
    'signature' => 'فريق سكن',

    'all_rights_reserved' => 'جميع الحقوق محفوظة.',
];
