<?php

return [
    'accepted' => 'يجب قبول حقل :attribute.',
    'accepted_if' => 'يجب قبول حقل :attribute عندما يكون :other مساوياً لـ :value.',
    'active_url' => 'حقل :attribute ليس عنواناً إلكترونياً صحيحاً.',
    'after' => 'يجب أن يكون حقل :attribute تاريخاً بعد :date.',
    'after_or_equal' => 'يجب أن يكون حقل :attribute تاريخاً بعد أو مساوياً لـ :date.',
    'alpha' => 'يمكن لحقل :attribute أن يحتوي على أحرف فقط.',
    'alpha_dash' => 'يمكن لحقل :attribute أن يحتوي على أحرف وأرقام والشرطات والشرطات السفلية فقط.',
    'alpha_num' => 'يمكن لحقل :attribute أن يحتوي على أحرف وأرقام فقط.',
    'array' => 'يجب أن يكون حقل :attribute مصفوفة.',
    'before' => 'يجب أن يكون حقل :attribute تاريخاً قبل :date.',
    'before_or_equal' => 'يجب أن يكون حقل :attribute تاريخاً قبل أو مساوياً لـ :date.',
    'between' => [
        'numeric' => 'يجب أن تكون قيمة حقل :attribute بين :min و :max.',
        'file' => 'يجب أن يكون حجم ملف :attribute بين :min و :max كيلوبايت.',
        'string' => 'يجب أن يكون طول نص حقل :attribute بين :min و :max أحرف.',
        'array' => 'يجب أن يحتوي حقل :attribute على بين :min و :max عنصراً.',
    ],
    'boolean' => 'يجب أن تكون قيمة حقل :attribute إما صحيح أو خطأ.',
    'confirmed' => 'تأكيد حقل :attribute غير متطابق.',
    'current_password' => 'كلمة المرور غير صحيحة.',
    'date' => 'حقل :attribute ليس تاريخاً صحيحاً.',
    'date_equals' => 'يجب أن يكون حقل :attribute تاريخاً مساوياً لـ :date.',
    'date_format' => 'حقل :attribute لا يطابق الصيغة :format.',
    'declined' => 'يجب أن يتم رفض حقل :attribute.',
    'declined_if' => 'يجب أن يتم رفض حقل :attribute عندما يكون :other مساوياً لـ :value.',
    'different' => 'يجب أن يكون حقل :attribute و :other مختلفين.',
    'digits' => 'يجب أن يكون حقل :attribute مكوناً من :digits أرقام.',
    'digits_between' => 'يجب أن يكون حقل :attribute مكوناً من بين :min و :max أرقام.',
    'dimensions' => 'أبعاد الصورة في حقل :attribute غير صحيحة.',
    'distinct' => 'حقل :attribute يحتوي على قيمة مكررة.',
    'email' => 'يجب أن يكون حقل :attribute عنواناً بريديً صحيحاً.',
    'ends_with' => 'يجب أن ينتهي حقل :attribute بأحد القيم التالية: :values.',
    'exists' => 'القيمة المحددة في حقل :attribute غير موجودة.',
    'file' => 'يجب أن يكون حقل :attribute ملفاً.',
    'filled' => 'حقل :attribute يجب أن يحتوي على قيمة.',
    'gt' => [
        'numeric' => 'يجب أن تكون قيمة حقل :attribute أكبر من :value.',
        'file' => 'يجب أن يكون حجم ملف :attribute أكبر من :value كيلوبايت.',
        'string' => 'يجب أن يكون طول نص حقل :attribute أكبر من :value أحرف.',
        'array' => 'يجب أن يحتوي حقل :attribute على أكثر من :value عنصراً.',
    ],
    'gte' => [
        'numeric' => 'يجب أن تكون قيمة حقل :attribute أكبر من أو مساوية لـ :value.',
        'file' => 'يجب أن يكون حجم ملف :attribute أكبر من أو مساوياً لـ :value كيلوبايت.',
        'string' => 'يجب أن يكون طول نص حقل :attribute أكبر من أو مساوياً لـ :value أحرف.',
        'array' => 'يجب أن يحتوي حقل :attribute على :value عناصر أو أكثر.',
    ],
    'image' => 'يجب أن يكون حقل :attribute صورة.',
    'in' => 'القيمة المحددة في حقل :attribute غير صحيحة.',
    'in_array' => 'حقل :attribute يجب أن يكون موجوداً في :other.',
    'integer' => 'يجب أن يكون حقل :attribute عدداً صحيحاً.',
    'ip' => 'يجب أن يكون حقل :attribute عنوان IP صحيحاً.',
    'ipv4' => 'يجب أن يكون حقل :attribute عنوان IPv4 صحيحاً.',
    'ipv6' => 'يجب أن يكون حقل :attribute عنوان IPv6 صحيحاً.',
    'json' => 'يجب أن يكون حقل :attribute نصاً بصيغة JSON صحيحة.',
    'lt' => [
        'numeric' => 'يجب أن تكون قيمة حقل :attribute أقل من :value.',
        'file' => 'يجب أن يكون حجم ملف :attribute أقل من :value كيلوبايت.',
        'string' => 'يجب أن يكون طول نص حقل :attribute أقل من :value أحرف.',
        'array' => 'يجب أن يحتوي حقل :attribute على أقل من :value عنصراً.',
    ],
    'lte' => [
        'numeric' => 'يجب أن تكون قيمة حقل :attribute أقل من أو مساوية لـ :value.',
        'file' => 'يجب أن يكون حجم ملف :attribute أقل من أو مساوياً لـ :value كيلوبايت.',
        'string' => 'يجب أن يكون طول نص حقل :attribute أقل من أو مساوياً لـ :value أحرف.',
        'array' => 'يجب أن يحتوي حقل :attribute على :value عناصر أو أقل.',
    ],
    'max' => [
        'numeric' => 'يجب أن تكون قيمة حقل :attribute أقل من أو مساوية لـ :max.',
        'file' => 'يجب أن يكون حجم ملف :attribute أقل من أو مساوياً لـ :max كيلوبايت.',
        'string' => 'يجب أن يكون طول نص حقل :attribute أقل من أو مساوياً لـ :max أحرف.',
        'array' => 'يجب أن يحتوي حقل :attribute على :max عناصر أو أقل.',
    ],
    'mimes' => 'يجب أن يكون حقل :attribute ملف من نوع :values.',
    'mimetypes' => 'يجب أن يكون حقل :attribute ملف من نوع :values.',
    'min' => [
        'numeric' => 'يجب أن تكون قيمة حقل :attribute على الأقل :min.',
        'file' => 'يجب أن يكون حجم ملف :attribute على الأقل :min كيلوبايت.',
        'string' => 'يجب أن يكون طول نص حقل :attribute على الأقل :min أحرف.',
        'array' => 'يجب أن يحتوي حقل :attribute على الأقل على :min عنصراً.',
    ],
    'multiple_of' => 'يجب أن تكون قيمة حقل :attribute مضاعفة لـ :value.',
    'not_in' => 'القيمة المحددة في حقل :attribute غير صحيحة.',
    'not_regex' => 'صيغة حقل :attribute غير صحيحة.',
    'numeric' => 'يجب أن يكون حقل :attribute رقماً.',
    'password' => 'كلمة المرور غير صحيحة.',
    'present' => 'يجب أن يكون حقل :attribute موجوداً.',
    'regex' => 'صيغة حقل :attribute غير صحيحة.',
    'required' => 'حقل :attribute مطلوب.',
    'required_if' => 'حقل :attribute مطلوب عندما يكون :other مساوياً لـ :value.',
    'required_unless' => 'حقل :attribute مطلوب ما لم يكون :other مساوياً لـ :value.',
    'required_with' => 'حقل :attribute مطلوب عندما يكون :values موجوداً.',
    'required_with_all' => 'حقل :attribute مطلوب عندما تكون :values موجودة.',
    'required_without' => 'حقل :attribute مطلوب عندما لا يكون :values موجوداً.',
    'required_without_all' => 'حقل :attribute مطلوب عندما لا تكون أي من :values موجودة.',
    'same' => 'يجب أن يطابق حقل :attribute مع حقل :other.',
    'size' => [
        'numeric' => 'يجب أن تكون قيمة حقل :attribute مساوية لـ :size.',
        'file' => 'يجب أن يكون حجم ملف :attribute مساوياً لـ :size كيلوبايت.',
        'string' => 'يجب أن يكون طول نص حقل :attribute مساوياً لـ :size أحرف.',
        'array' => 'يجب أن يحتوي حقل :attribute على :size عنصراً.',
    ],
    'starts_with' => 'يجب أن يبدأ حقل :attribute بأحد القيم التالية: :values.',
    'string' => 'يجب أن يكون حقل :attribute نصاً.',
    'timezone' => 'يجب أن يكون حقل :attribute منطقة زمنية صحيحة.',
    'unique' => 'قيمة حقل :attribute موجودة بالفعل.',
    'uploaded' => 'فشل تحميل حقل :attribute.',
    'url' => 'صيغة حقل :attribute غير صحيحة.',
    'uuid' => 'يجب أن يكون حقل :attribute UUID صحيحاً.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'custom-message',
        ],
    ],
    'attributes' => [],
];
