<?php

return [
    'legal_documents' => [
        'acceptances_for' => 'Acceptances for :type v:version',
        'total_acceptances' => 'total acceptances',
        'search_user_email' => 'Search by username or email',
        'search' => 'Search',
        'user' => 'User',
        'email' => 'Email',
        'accepted_at' => 'Accepted At',
        'ip_address' => 'IP Address',
        'browser' => 'Browser',
        'na' => 'N/A',
        'no_acceptances' => 'No acceptances yet',

        'new_version' => 'New Version',
        'create_trigger' => 'Create a new version to trigger re-acceptance from all users',
        'latest_version' => 'Latest Version',
        'version_colon' => 'Version:',
        'published_colon' => 'Published:',
        'version_number' => 'Version Number',
        'versioning_hint' => 'Use semantic versioning (v1.0) or date-based versioning',
        'document_content' => 'Document Content',
        'document_content_en' => 'Document Content (English)',
        'document_content_ar' => 'Document Content (Arabic)',
        'enter_content' => 'Enter the full content of the :type',
        'html_hint' => 'You can use HTML for formatting',
        'structure_hint_title' => 'Recommended structure',
        'structure_hint_body' => 'Use headings with <code>id</code> attributes and put the details under each heading. Example:<br><code>&lt;h2 id="data-usage"&gt;Data Usage&lt;/h2&gt;</code><br><code>&lt;p&gt;...details...&lt;/p&gt;</code><br><code>&lt;h2 id="cookies"&gt;Cookies&lt;/h2&gt;</code><br><code>&lt;p&gt;...details...&lt;/p&gt;</code>',
        'publish_confirm' => 'Publishing this version will require all users to accept the new :type before continuing',
        'cancel' => 'Cancel',
        'publish_version' => 'Publish Version',

        'management' => 'Legal Documents Management',
        'manage_publish' => 'Manage and publish new versions of terms and privacy policies',
        'terms' => 'Terms & Conditions',
        'policy' => 'Privacy Policy',
        'version' => 'Version',
        'active' => 'Active',
        'archived' => 'Archived',
        'no_versions' => 'No versions published yet',
        'create_first_version' => 'Create First Version',
        'how_it_works' => 'How It Works',
        'trigger_reaccept' => 'Create a new version of a document to trigger re-acceptance from all users',
        'auto_archive' => 'Previous versions are automatically archived when a new version is published',
        'user_modal' => 'Users will see a modal prompting them to accept the new version',
        'acceptance_tracking' => 'All acceptances are tracked with IP address, user agent, and timestamp',

        'back' => 'Back',
        'version_details' => 'Document Version Details',
        'type' => 'Type',
        'published' => 'Published',
        'content_preview' => 'Content Preview',
        'acceptance_stats' => 'Acceptance Stats',
        'users_accepted' => 'Users Accepted',
        'users_still_need' => 'users still need to accept',
        'actions' => 'Actions',
        'view_acceptances' => 'View Acceptances',
        'create_new_version' => 'Create New Version',
        'archived_info' => 'This version has been archived. Create a new version to make users accept updated terms.',
    ],

    'listings' => [
        'manage' => 'Manage Listings',
        'view_manage_all' => 'View and manage all listings in the system',
        'search_placeholder' => 'Search by title',
        'all_status' => 'All Status',
        'title' => 'Title',
        'user' => 'User',
        'status_col' => 'Status',
        'price' => 'Price',
        'created' => 'Created',
        'actions' => 'Actions',
        'no_more_to_load' => 'No more listings to load',

        'approve' => 'Approve',
        'reject' => 'Reject',
        'already_reviewed' => 'This listing has already been reviewed.',
        'back_to_pending' => 'Back to Pending Listings',
        'approve_listing' => 'Approve Listing',
        'approve_confirm' => 'Are you sure you want to approve this listing? The property will be published.',
        'reject_listing' => 'Reject Listing',
        'reject_confirm' => 'Are you sure you want to reject this listing? The user will be notified.',

        'status' => [
            'pending' => 'Pending',
            'approved' => 'Approved',
            'rejected' => 'Rejected',
            'sold' => 'Sold',
            'archived' => 'Archived',
        ],

        'na' => 'N/A',
        'preview' => 'Preview',
        'none_found' => 'No listings found',
    ],

    'reports' => [
        'review_title' => 'Review Report',
        'review_annotate' => 'Review and annotate this report',
        'no_broker' => 'No Broker',
        'view_details' => 'View Details',
        'listing_not_available' => 'Listing not available',
        'details' => 'Report Details',
        'reason' => 'Reason:',
        'description' => 'Description:',
        'comment_optional' => 'Comment (optional)',
        'add_note' => 'Add a short note about the review',
        'set_reviewed' => 'Set Reviewed',
        'back' => 'Back',
        'only_admins' => 'Only administrators can review reports.',
        'reviewed' => 'Reviewed',
        'reviewed_by' => 'Reviewed by',
        'comment' => 'Comment',
        'back_to_reports' => 'Back to reports',
        'delete_modal_title' => 'Delete Report',
        'delete_modal_body' => 'Are you sure you want to delete this report? This action cannot be undone.',
        'delete_modal_cancel' => 'Cancel',
        'delete_modal_confirm' => 'Delete',
    ],

    'trust_requests' => [
        'management' => 'Trust Requests Management',
        'review_manage' => 'Review and manage user trust verification requests',
        'user' => 'User',
        'email' => 'Email',
        'phone' => 'Phone',
        'status' => 'Status',
        'submitted' => 'Submitted',
        'action' => 'Action',
        'pending' => 'Pending',
        'approved' => 'Approved',
        'declined' => 'Declined',
        'review' => 'Review',
        'none_found' => 'No trust requests found',
        'na' => 'N/A',

        'back' => 'Back',
        'review_title' => 'Trust Request Review',
        'cancel' => 'Cancel',
        'decline' => 'Decline',
    ],

    'users' => [
        'manage' => 'Manage Users',
        'view_manage_all' => 'View and manage all users in the system',
        'search_placeholder' => 'Search by name, email, or username',
        'all_status' => 'All Status',
        'banned' => 'Banned',
        'admin' => 'Admin',
        'moderator' => 'Moderator',
        'broker' => 'Broker',
        'user' => 'User',
        'avatar' => 'Avatar',
        'name' => 'Name',
        'status' => 'Status',
        'date_joined' => 'Date Joined',
        'details' => 'Details',

        'manage_label' => 'Manage Users',
        'no_more_users' => 'No more users to load',
        'loading_more_users' => 'Loading more users...',

        'user_details' => 'User Details',
        'back' => 'Back',
        'personal_info' => 'Personal Information',
        'nickname' => 'Nickname',
        'username' => 'Username',
        'phone' => 'Phone',
        'role' => 'Role',
        'trust_status' => 'Trust Status',
        'account_details' => 'Account Details',
        'email_verified' => 'Email Verified',
        'not_verified' => 'Not Verified',
        'member_since' => 'Member Since',
        'last_updated' => 'Last Updated',
        'trust_level' => 'Trust Level',
        'actions' => 'Actions',
        'ban' => 'Ban User',
        'unban' => 'Unban User',
        'restrict' => 'Restrict User',
        'revoke_moderator' => 'Revoke Moderator',
        'make_moderator' => 'Make Moderator',
        'ban_reason' => 'Ban Reason',
        'ban_reason_placeholder' => 'Enter the reason for banning this user',
        'cancel' => 'Cancel',
        'unban_confirm' => 'Are you sure you want to unban this user?',
        'restrict_confirm' => 'Are you sure you want to restrict this user? They will be unable to list items.',
        'admin_password' => 'Admin Password',
        'admin_password_placeholder' => 'Enter your admin password to confirm',
        'revoke_moderator_confirm' => 'Are you sure you want to revoke moderator status from this user?',
        'make_moderator_confirm' => 'Are you sure you want to promote this user to moderator?',
        'statistics' => 'Statistics',
        'active_listings' => 'Active Listings',
        'sold_listings' => 'Sold Listings',
        'total_listings' => 'Total Listings',
    ],

    'dashboard' => [
        'quick_actions' => 'Quick Actions',
        'view_trust_requests' => 'View Trust Requests',
        'review_listings' => 'Review Listings',
        'settings' => 'Settings',
        'total_users' => 'Total Users',
        'total_listings' => 'Total Listings',
        'reports' => 'Reports',
        'trusted_users' => 'Trusted Users',
        'sold_listings' => 'Sold Listings',
    ],

    'pending_listings' => [
        'title' => 'Title',
        'user' => 'User',
        'location' => 'Location',
        'price' => 'Price',
        'actions' => 'Actions',
        'republish_badge' => 'Republish',
        'review_and_approve' => 'Review and approve pending listings',
        'preview' => 'Preview',
        'approve' => 'Approve',
        'reject' => 'Reject',
        'approve_modal_title' => 'Approve Listing',
        'approve_modal_body' => 'Are you sure you want to approve this listing? The property will be published.',
        'cancel' => 'Cancel',
        'reject_modal_title' => 'Reject Listing',
        'reject_modal_body' => 'Are you sure you want to reject this listing? The user will be notified.',
    ],

    'pending_users' => [
        'header' => 'Pending Users',
        'subheader' => 'Review and approve pending user registrations',
        'username' => 'Username',
        'email' => 'Email',
        'submitted_data' => 'Submitted Data',
        'view_data' => 'View Data',
        'approve' => 'Approve',
        'reject' => 'Reject',
        'actions' => 'Actions',
    ],

    'reports_page' => [
        'header' => 'Reports',
        'subheader' => 'View and manage listing reports',
        'search_placeholder' => 'Search by listing, reporter or reason',
        'all_status' => 'All Status',
        'pending' => 'Pending',
        'reviewed' => 'Reviewed',
        'filter' => 'Filter',
        'listing' => 'Listing',
        'reporter' => 'Reporter',
        'reason' => 'Reason',
        'status' => 'Status',
        'created' => 'Created',
        'no_actions' => 'No actions',
    ],

    'misc' => [
        'users_statistics' => 'Users Statistics',
        'listings_statistics' => 'Listings Statistics',
        'enter_email_reset' => "Enter your email address and we'll send you a link to reset your password.",
        'account_banned' => 'Account Banned',
        'account_suspended' => 'Account Suspended',
        'username_colon' => 'Username:',
        'account_suspended_message' => 'Your account has been suspended by our administration team.',
        'believe_incorrect' => 'If You Believe This Is Incorrect',
        'contact_support_prompt' => "Please contact our support team with your username and account details. We're here to help resolve this issue.",
        'contact_support' => 'Contact Support',
        'processing' => 'Processing...',
        'no_pending_agreements' => 'No pending agreements',
        'accepted_thanks' => 'Thank you! You have accepted our terms and policy',
        'error_accepting' => 'Error accepting agreements',
        'arabic' => 'Arabic',
        'english' => 'English',
    ],

    'email' => [
        'trust_accepted_headline' => 'Your Trust Verification is Approved!',
        'trust_accepted_greeting' => 'Hello :name,',
        'trust_accepted_intro' => 'Congratulations! Your trust verification request has been approved.',
        'trust_accepted_verified' => 'You are now a verified user on Sakan.',
        'trust_accepted_next_steps' => 'What can you do next?',
        'trust_accepted_can_post' => 'You can now post listings and enjoy all features.',
        'trust_accepted_button' => 'Post a New Listing',

        'trust_rejected_headline' => 'Trust Verification Declined',
        'trust_rejected_greeting' => 'Hello :name,',
        'trust_rejected_intro' => 'Unfortunately, your trust verification request was declined by our team.',
        'trust_rejected_reason_title' => 'Reason for Decline',
        'trust_rejected_what_to_do' => 'What should you do?',
        'trust_rejected_resubmit' => 'You can review your information and resubmit your request.',
        'trust_rejected_button' => 'Resubmit Verification Request',

        'points_added_headline' => 'Points Added to Your Account',
        'points_added_greeting' => 'Hello :name,',
        'points_added_received' => 'You have received :points points.',
        'points_added_reason' => 'Reason: :reason',
        'points_added_reason_default' => 'Points credited by admin.',
        'points_added_your_points' => 'Your Points Balance',
        'points_added_balance' => 'You now have :points points.',
        'points_added_uses' => 'You can use your points to:',
        'points_added_use1' => 'Post new listings',
        'points_added_use2' => 'Upgrade your plan',
        'points_added_use3' => 'Unlock premium features',
        'points_added_use4' => 'Participate in promotions',
        'points_added_button' => 'Go to Points Store',
        'points_added_thanks' => 'Thank you for using Sakan!',

        'listing_approved_headline' => 'Your Listing is Approved!',
        'listing_approved_greeting' => 'Hello :name,',
        'listing_approved_intro' => 'Your listing ":title" has been approved and is now live.',
        'listing_approved_visibility' => 'Your listing is now visible to all users.',
        'listing_approved_whats_next' => "What's next?",
        'listing_approved_action1' => 'Share your listing with friends',
        'listing_approved_action2' => 'Respond to inquiries quickly',
        'listing_approved_action3' => 'Keep your listing updated',
        'listing_approved_action4' => 'Mark as sold when rented',
        'listing_approved_button' => 'View Listing',
        'listing_approved_footer' => 'Thank you for using Sakan!',

        'listing_rejected_headline' => 'Your Listing Was Rejected',
        'listing_rejected_greeting' => 'Hello :name,',
        'listing_rejected_intro' => 'Your listing ":title" was not approved.',
        'listing_rejected_reason' => 'Reason: :reason',
        'listing_rejected_reason_default' => 'Not specified.',
        'listing_rejected_can_do' => 'What can you do?',
        'listing_rejected_action1' => 'Edit your listing',
        'listing_rejected_action2' => 'Check our guidelines',
        'listing_rejected_action3' => 'Contact support',
        'listing_rejected_action4' => 'Resubmit for review',
        'listing_rejected_guidelines' => 'Guidelines:',
        'listing_rejected_guideline1' => 'No prohibited content',
        'listing_rejected_guideline2' => 'Accurate information only',
        'listing_rejected_guideline3' => 'No duplicate listings',
        'listing_rejected_guideline4' => 'Respect our terms',
        'listing_rejected_resubmit' => 'You can edit and resubmit your listing for review.',

        'listing_expired_headline' => 'Your Listing Has Expired',
        'listing_expired_greeting' => 'Hello :name,',
        'listing_expired_intro' => 'Your listing ":title" has expired.',
        'listing_expired_duration' => 'Listings are active for a limited time.',
        'listing_expired_reactivate_title' => 'How to Reactivate',
        'listing_expired_reactivate_intro' => 'You can reactivate your listing from your dashboard.',
        'listing_expired_button' => 'View Listing',
        'listing_expired_tips' => 'Tips:',
        'listing_expired_tip1' => 'Update your listing details',
        'listing_expired_tip2' => 'Check your plan status',
        'listing_expired_tip3' => 'Contact support if needed',
        'listing_expired_tip4' => 'Promote your listing',
        'listing_expired_urgency' => 'Reactivate soon to avoid losing potential tenants.',

        'listing_sold_prompt_headline' => 'You have :count applications! Mark as sold?',
        'listing_sold_prompt_greeting' => 'Hello :name,',
        'listing_sold_prompt_intro' => 'Your listing ":title" has received :count applications.',
        'listing_sold_prompt_action' => 'If your property is rented, mark it as sold.',
        'listing_sold_prompt_mark_button' => 'Mark as Sold',
        'listing_sold_prompt_why_mark' => 'Why mark as sold?',
        'listing_sold_prompt_benefit1' => 'Helps us keep listings up to date',
        'listing_sold_prompt_benefit2' => 'Improves your reputation',
        'listing_sold_prompt_benefit3' => 'Notifies interested users',
        'listing_sold_prompt_benefit4' => 'Unlocks new features',
        'listing_sold_prompt_other_actions' => 'If not rented, you can ignore this message.',
        'listing_sold_prompt_thanks' => 'Thank you for using Sakan!',
    ],
];
