<?php

return [
    'subject_user_welcome' => 'Welcome to Sakan!',
    'subject_trust_request_accepted' => 'Your Trust Request Was Accepted',
    'subject_trust_request_rejected' => 'Your Trust Request Was Declined',
    'subject_listing_approved' => 'Your Listing Has Been Approved',
    'subject_listing_rejected' => 'Your Listing Was Rejected',
    'subject_listing_expired' => 'Your Listing Has Expired',
    'subject_points_added' => 'Points Added to Your Account',
    'subject_listing_sold_prompt' => 'Your Listing Has Multiple Applications',
    'subject_plan_auto_renew_insufficient' => 'Add Points to Renew Your Plan',
    'subject_default' => 'Notification from Sakan',

    'welcome_headline' => 'Welcome to Sakan!',
    'welcome_greeting' => 'Hello :name,',
    'welcome_intro' => 'We are thrilled to have you join our community.',
    'welcome_account_created' => 'Your account has been created successfully.',
    'welcome_whats_next' => "What's next?",
    'welcome_step1' => 'Complete your profile.',
    'welcome_step2' => 'Verify your email address.',
    'welcome_step3' => 'Browse listings and save your favorites.',
    'welcome_step4' => 'Post your first listing when you are ready.',
    'welcome_support' => 'If you need any help, just reply to this email and we will assist you.',
    'welcome_button' => 'Verify Email',
    'welcome_footer' => 'Best regards',

    'trust_accepted_headline' => 'Your Trust Verification is Approved!',
    'trust_accepted_greeting' => 'Hello :name,',
    'trust_accepted_intro' => 'Congratulations! Your trust verification request has been approved.',
    'trust_accepted_verified' => 'You are now a verified user on Sakan.',
    'trust_accepted_next_steps' => 'What can you do next?',
    'trust_accepted_can_post' => 'You can now post listings and enjoy all features.',
    'trust_accepted_button' => 'Post a New Listing',

    'trust_rejected_headline' => 'Trust Verification Declined',
    'trust_rejected_greeting' => 'Hello :name,',
    'trust_rejected_intro' => 'Unfortunately, your trust verification request was declined by our team.',
    'trust_rejected_reason_title' => 'Reason for Decline',
    'trust_rejected_what_to_do' => 'What should you do?',
    'trust_rejected_resubmit' => 'You can review your information and resubmit your request.',
    'trust_rejected_button' => 'Resubmit Verification Request',

    'points_added_headline' => 'Points Added to Your Account',
    'points_added_greeting' => 'Hello :name,',
    'points_added_received' => 'You have received :points points.',
    'points_added_reason' => 'Reason: :reason',
    'points_added_reason_default' => 'Points credited by admin.',
    'points_added_your_points' => 'Your Points Balance',
    'points_added_balance' => 'You now have :points points.',
    'points_added_uses' => 'You can use your points to:',
    'points_added_use1' => 'Post new listings',
    'points_added_use2' => 'Upgrade your plan',
    'points_added_use3' => 'Unlock premium features',
    'points_added_use4' => 'Participate in promotions',
    'points_added_button' => 'Go to Points Store',
    'points_added_thanks' => 'Thank you for using Sakan!',

    'listing_approved_headline' => 'Your Listing is Approved!',
    'listing_approved_greeting' => 'Hello :name,',
    'listing_approved_intro' => 'Your listing ":title" has been approved and is now live.',
    'listing_approved_visibility' => 'Your listing is now visible to all users.',
    'listing_approved_whats_next' => "What's next?",
    'listing_approved_action1' => 'Share your listing with friends',
    'listing_approved_action2' => 'Respond to inquiries quickly',
    'listing_approved_action3' => 'Keep your listing updated',
    'listing_approved_action4' => 'Mark as sold when rented',
    'listing_approved_button' => 'View Listing',
    'listing_approved_footer' => 'Thank you for using Sakan!',

    'listing_rejected_headline' => 'Your Listing Was Rejected',
    'listing_rejected_greeting' => 'Hello :name,',
    'listing_rejected_intro' => 'Your listing ":title" was not approved.',
    'listing_rejected_reason' => 'Reason: :reason',
    'listing_rejected_reason_default' => 'Not specified.',
    'listing_rejected_can_do' => 'What can you do?',
    'listing_rejected_action1' => 'Edit your listing',
    'listing_rejected_action2' => 'Check our guidelines',
    'listing_rejected_action3' => 'Contact support',
    'listing_rejected_action4' => 'Resubmit for review',
    'listing_rejected_guidelines' => 'Guidelines:',
    'listing_rejected_guideline1' => 'No prohibited content',
    'listing_rejected_guideline2' => 'Accurate information only',
    'listing_rejected_guideline3' => 'No duplicate listings',
    'listing_rejected_guideline4' => 'Respect our terms',
    'listing_rejected_resubmit' => 'You can edit and resubmit your listing for review.',

    'listing_expired_headline' => 'Your Listing Has Expired',
    'listing_expired_greeting' => 'Hello :name,',
    'listing_expired_intro' => 'Your listing ":title" has expired.',
    'listing_expired_duration' => 'Listings are active for a limited time.',
    'listing_expired_reactivate_title' => 'How to Reactivate',
    'listing_expired_reactivate_intro' => 'You can reactivate your listing from your dashboard.',
    'listing_expired_button' => 'View Listing',
    'listing_expired_tips' => 'Tips:',
    'listing_expired_tip1' => 'Update your listing details',
    'listing_expired_tip2' => 'Check your plan status',
    'listing_expired_tip3' => 'Contact support if needed',
    'listing_expired_tip4' => 'Promote your listing',
    'listing_expired_urgency' => 'Reactivate soon to avoid losing potential tenants.',

    'listing_sold_prompt_headline' => 'You have :count applications! Mark as sold?',
    'listing_sold_prompt_greeting' => 'Hello :name,',
    'listing_sold_prompt_intro' => 'Your listing ":title" has received :count applications.',
    'listing_sold_prompt_action' => 'If your property is rented, mark it as sold.',
    'listing_sold_prompt_mark_button' => 'Mark as Sold',
    'listing_sold_prompt_why_mark' => 'Why mark as sold?',
    'listing_sold_prompt_benefit1' => 'Helps us keep listings up to date',
    'listing_sold_prompt_benefit2' => 'Improves your reputation',
    'listing_sold_prompt_benefit3' => 'Notifies interested users',
    'listing_sold_prompt_benefit4' => 'Unlocks new features',
    'listing_sold_prompt_other_actions' => 'If not rented, you can ignore this message.',
    'listing_sold_prompt_thanks' => 'Thank you for using Sakan!',

    'plan_auto_renew_insufficient_headline' => 'Not enough points to auto-renew your plan',
    'plan_auto_renew_insufficient_greeting' => 'Hello :name,',
    'plan_auto_renew_insufficient_body' => 'Your ":plan" plan will expire on :date. Auto-renew is enabled, but you need :cost points and you currently have :balance points.',
    'plan_auto_renew_insufficient_cta' => 'Buy points now to keep your listings active.',
    'plan_auto_renew_insufficient_button' => 'Buy Points',

    'signature_closing' => 'Regards',
    'signature' => 'The Sakan Team',

    'all_rights_reserved' => 'All rights reserved.',
];
